In [6]:
import numpy as np
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
df = pd.read_csv (r'C:\Users\khaldoun\Desktop\Data 2015 to 2019.csv')



In [7]:
#  load data 
df = pd.read_csv (r'C:\Users\khaldoun\Desktop\Data 2015 to 2019.csv')

#converdata to dataframe 
data = np.array(df)


In [8]:
# in this part I will organize the data data in a way that each raw has the temprature of the day in addtion to the temprature of the 8 days before it.
# the result will be a list of lists ( each list have 8 items)
training_data = []
l= []
for i in range(1085):
    for j in range(8):
        l.append(int(data[i+j][1]))
    training_data.insert(i,l)
    l=[]
        
   

In [9]:
# Covert list to an array for easy manipulation 

final_data = np.array(training_data)


In [23]:
final_data[0]

array([ 3,  2,  0,  1,  0, -3, -2,  0])

In [10]:
# in this part I will split the data into training data and results data. the result will be the last day and the training will be the 7 days before
results = final_data[:,-1]
desc = final_data[:,0:-1]

In [30]:
# in this part I prepare the data in a matrix to feed it to the predictive AI . 

#results = results.reshape(-1,1)
#desc = desc.reshape(1085,7)

results = pd.Series(np.array(results))
# intiate the AI 
neigh = KNeighborsClassifier(n_neighbors=1, p = 7)

# train the AI 

neigh.fit(desc, results)

KNeighborsClassifier(n_neighbors=1, p=7)

In [31]:
neigh.predict(np.array([[3,  2,  0,  1,  0, -3, -2] ]))

array([0])

In [21]:
desc[0]


array([ 3,  2,  0,  1,  0, -3, -2])

In [19]:
desc.shape

(1085, 7)