In [5]:
import numpy as np
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
df = pd.read_csv ("Data 2015 to 2019.csv")



In [6]:


#converdata to dataframe 
data = np.array(df)


In [7]:
# in this part I will organize the data data in a way that each raw has the temprature of the day in addtion to the temprature of the 8 days before it.
# the result will be a list of lists ( each list have 8 items)
training_data = []
l= []
for i in range(1085):
    for j in range(8):
        l.append(int(data[i+j][1]))
    training_data.insert(i,l)
    l=[]
        
   

[]

In [8]:
# Covert list to an array for easy manipulation 

final_data = np.array(training_data)


[[ 3  2  0 ... -3 -2  0]
 [ 2  0  1 ... -2  0  0]
 [ 0  1  0 ...  0  0  1]
 ...
 [ 7  7  6 ...  7  6  5]
 [ 7  6  7 ...  6  5  7]
 [ 6  7  6 ...  5  7  4]]


In [9]:
# in this part I will split the data into training data and results data. the result will be the last day and the training will be the 7 days before
results = final_data[:,-1]
desc = final_data[:,0:-1]

In [10]:
# in this part I prepare the data in a matrix to feed it to the predictive AI . 

results = results.reshape(-1,1)
desc = desc.reshape(1085,7)

# intiate the AI 
neigh = KNeighborsClassifier(n_neighbors=3)

# train the AI 

neigh.fit(results, desc)

KNeighborsClassifier(n_neighbors=3)

In [ ]:
# now I need to learn how use the AI XD 


KNeighborsClassifier(n_neighbors=3)
